# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20160719_0414'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_auto_20160719_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_singlemessages', to='chat.SingleChat')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_singlemessages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
