# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-25 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160721_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profilepic',
            field=models.ImageField(default='static/profilepics/pp.jpg', upload_to='static/profilepics/'),
        ),
    ]
