# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160825_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profilepic',
            field=models.ImageField(default='static/profilepics/anonymous.jpg', upload_to='static/profilepics/', verbose_name='Profile Pic'),
        ),
    ]
