# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-02 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170403_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='privatekey',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='publickey',
        ),
    ]
