# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='Group name', max_length=20),
        ),
    ]
