# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 21:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20160719_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechat',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='singlechat',
            name='user',
            field=models.ManyToManyField(related_name='singlechatrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
