# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20160719_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechat',
            name='title',
            field=models.CharField(blank=True, default='SingleChat', max_length=20),
        ),
    ]
